### PR TITLE
Fix text overflow on multiple places

### PR DESCRIPTION
**Pull request by maurofmferrao**
relates to xibosignage/xibo#3328

 - Viewer bottom bar
 - Widget in Playlist view
 - External Playlist editor header

### CODE REVIEW

**Comment by maurofmferrao** [comment]
TEST: /Layout/Editor /Library END

**Review by dasgarner — APPROVED** [review]

**Comment by maurofmferrao** [comment]
TEST: /Layout/Editor, /Library END

**Comment by ifarzana** [comment]
TEST: /Layout/Editor/playlists.cy.js END

**Comment by maurofmferrao** [comment]
TEST: /Library/playlists.cy.js END

**Pull request merged**
