### PR TITLE
Remove console.log from xiboIC

### PR DESCRIPTION
**Pull request by maurofmferrao**
relates to xibosignageltd/xibo-private#608

### CODE REVIEW

**Comment by maurofmferrao** [comment]
TEST: /Layout/Editor END

**Review by dasgarner — CHANGES_REQUESTED** [review]
Looks like you've got an enormous delta in package.lock again - are you running npm install with the right version of node?

**Comment by maurofmferrao** [comment]
> Looks like you've got an enormous delta in package.lock again - are you running npm install with the right version of node?

I think node's version might be the issue... What version should I be using?

**Comment by dasgarner** [comment]
Node 12

**Comment by maurofmferrao** [comment]
TEST: /Layout/Editor END

**Review by dasgarner — APPROVED** [review]

**Pull request merged**
