### PR TITLE
Forecast IO Template

### PR DESCRIPTION
**Pull request by dasgarner**
...-day-current-day-big-circle.template.json

Template for the forecastIO module. 5 days forecast. Current day in a big circle, other four days small. Contains link to google font. Contains javascript and fixed array in javascript for three day abbreviation.

Please let me know if this meets your standards.

### CODE REVIEW

**Comment by dasgarner** [comment]
@MedusaDelft I have created this pull request to discuss getting your template included into the main Xibo (if you wanted to do that).

There are some blocks at the moment - I am not sure if you'd be willing to tidy these up:
 1. Sign the CLA
 2. Remove the attribution to Medusa Computer Creations from the name of the template (leaving it in the HTML if you wanted)
 3. Update to use the new [time|FORMAT] substitution, where format is the PHP date format for the local time, i.e. D for weekday
 4. Update to use the rounded temperatureMaxFloor substitution
 5. 3&4 mean the JavaScript can be removed

Its a really nice template, it would be great to include it.

**Comment by MedusaDelft** [comment]
@dasgarner Made the requested changes.

**Comment by MedusaDelft** [comment]
@dasgarner Using the dev-branch of today (hour ago), I do not see the forecast data anymore on a preview. (Cleared the complete cache from the library) 
Message in log:
4819 15-03-11 07:27:05 CMS Forecast\Forecast request Unable to reach twitter api. 

Sorry, no time currently to dig into this

**Comment by dasgarner** [comment]
Looks great - thank you. Just the [CLA](https://github.com/xibosignage/xibo/blob/master/CONTRIBUTING.md) if you don't mind. If you'd rather not sign the CLA I can put this template on the community forum instead, but people would have to manually apply it as we wont be able to distribute it with the release.

**Comment by MedusaDelft** [comment]
@dasgarner  I've created a pull request for the CLA as well.

**Comment by dasgarner** [comment]
You've created a pull within your own Fork - can you create the pull back to xibosignage/xibo:master ?
Cheers!

**Comment by MedusaDelft** [comment]
Oeps. Sorry! Done.

**Comment by dasgarner** [comment]
Cheers!!

**Pull request merged**
