### PR TITLE
Create RemoteDatasets

### PR DESCRIPTION
**Pull request by LukyLuke**
To be able to show/use Datas from remote systems fetched by JSON I'm introducing here the possibility of RemoteDatasets.

To concretise:
The new RemoteDatasets allows you to fetch and truncate Datasets based on JSON-Requests to other systems. The Remote-Calls are done with the new Task `RemoteDataSetFetchTask`.
The new Entity and Controller is based on the already existing ones from the DataSet to use all already existing functions based on them.

What's missing:
* Documentation :o)
* I am not aware of this PHP-Doc styles and tags
* Unit Tests (I've never worked with PHPUnit but with JUnit)

For the License: I hope I forgot nothing, I also can change all to xibo signange, just ping me for that.

NB: Don't be confused about the composer.phar stuff, that was added by mistake and reverted.
NB: This work I've done for change my xibo_rgraph module to only use DataSets and no direct JSON Calls (what makes problems due to (fucking) CORS)

### CODE REVIEW

**Comment by dasgarner** [comment]
Firstly, thank you for taking the time to develop this enhancement - it looks very interesting!

I've created a task to track the enhancement, so we can discuss and fully understand what you've done before merging it into the core.

We will also need you to take a look at the contributing readme, to make sure you're happy with the contributors licence agreement: https://github.com/xibosignage/xibo/blob/master/CONTRIBUTING.md

Unfortunately I am away for 3 weeks from this coming Wednesday - so there might be some delays before I can respond. Sorry about this!

**Comment by dasgarner** [comment]
I've created a new feature branch `feature/remote-datasets` please can you re-target the PR into that branch for the time being. Thanks!

**Comment by LukyLuke** [comment]
* CLA: done
* Re-Target to the feature branch: done
* Holidays: Have fun Dan :)

**Comment by LukyLuke** [comment]
@dasgarner Have you had already some time to check this?
You created a MileStone or Task or something like this for dicussions which I don't find anymore.

**Comment by dasgarner** [comment]
I've no had time to check it yet unfortunately - I will look in detail as soon as I can.

I did create a task to track the development [here](https://github.com/xibosignage/xibo/issues/1320), I've not assigned it to a milestone yet as I am not sure where it will fit in.

I did give it a lot of thought while I was away on holiday and the more I think about it, the more I like it as an idea! I just need to try it out, review the code and then decide whether it is safe to add it in a point release 1.8.4, or whether it will be a new release 1.9.0-alpha.

Thanks!

**Comment by dasgarner** [comment]
I'm merging this PR in so that I can pull the branch and look at it on my local dev installation. We can continue to discuss in the linked issue.

**Pull request merged**
