### PR TITLE
Collapsible Menu

### PR DESCRIPTION
**Pull request by laercionit**

### CODE REVIEW

**Comment by dasgarner** [comment]
Fantastic! That is just what we need...

Can you do two final things before we merge:
 1. Complete the CLA in xibosignage/xibo
 2. Move the contents of `override.css` to the end of `xibo.css`

Great! Thanks! :+1:

**Comment by laercionit** [comment]
Done.
I made sure this time? I'm still learning and teaching here the process.

*Laercio Junior*
Cel./Pessoal: (21) 99162-7440
Email Pessoal: laercionit@gmail.com
MSN: laercionit@hotmail.com
Skype: laercionit



2015-02-04 11:50 GMT-02:00 Dan Garner <notifications@github.com>:

**Comment by dasgarner** [comment]
Looks great - if you can sign the CLA in xibosignage/xibo then I will get this merged.

Thanks!

**Comment by laercionit** [comment]
Done.

*Laercio Junior*
Cel./Pessoal: (21) 99162-7440
Email Pessoal: laercionit@gmail.com
MSN: laercionit@hotmail.com
Skype: laercionit



2015-02-06 9:32 GMT-02:00 Dan Garner <notifications@github.com>:

**Comment by dasgarner** [comment]
I don't see it? https://github.com/xibosignage/xibo/pulls

See Step 3: filing the pull request https://github.com/xibosignage/xibo/blob/master/CONTRIBUTING.md

**Comment by laercionit** [comment]
Now Its OK?


*Laercio Junior*
Cel./Pessoal: (21) 99162-7440
Email Pessoal: laercionit@gmail.com
MSN: laercionit@hotmail.com
Skype: laercionit



2015-02-06 15:59 GMT-02:00 Dan Garner <notifications@github.com>:

**Comment by laercionit** [comment]
Dan, sorry if I did wrong, but I did not and still in the process.

I did PULL to developer Xibo-cms
Then I did the PULL with laercionit.md to Xibo
https://github.com/xibosignage/xibo/pulls

Is that or have something else to do?

*Laercio Junior*
Cel./Pessoal: (21) 99162-7440
Email Pessoal: laercionit@gmail.com
MSN: laercionit@hotmail.com
Skype: laercionit



2015-02-06 17:09 GMT-02:00 Laercio Mendonça <laercionit@gmail.com>:

**Comment by dasgarner** [comment]
You've got it sorted now. The CLA is signed and we can accept any pull requests from you now.

**Comment by laercionit** [comment]
I'll check the CSS files.

**Pull request merged**
