### PR TITLE
Text element: Adjust to area

### PR DESCRIPTION
**Pull request by maurofmferrao**
relates to xibosignageltd/xibo-private#664

### CODE REVIEW

**Review by dasgarner — APPROVED** [review]

**Comment by gracec20** [comment]
TEST: /Layout END

**Comment by gracec20** [comment]
TEST: /Layout/Editor/layout_editor_dataset.cy.js, /Layout/Editor/layout_editor_rss_ticker.cy.js END

**Comment by gracec20** [comment]
TEST: Layout/Editor/layout_editor_rss_ticker.cy.js END

**Comment by gracec20** [comment]
TEST: /Layout/Editor/layout_editor_rss_ticker.cy.js END

**Pull request merged**
