### PR TITLE
Cypress: Tests in relevant spec category

### PR DESCRIPTION
**Pull request by ifarzana**

### CODE REVIEW

**Comment by ifarzana** [comment]
TEST: all

**Review by maurofmferrao — CHANGES_REQUESTED** [review]
Since we're renaming/moving files, can we have all the tests that happen inside the Layout Editor to be renamed `layout_editor_[specificName].cy.js` and have them in a separate folder from the Layout Grid page?

**Comment by ifarzana** [comment]
TEST: all

**Comment by ifarzana** [comment]
TEST: /Administration/users.cy.js, /Layout/Layout Editor/layout_editor_dataset.cy.js END

**Review by maurofmferrao — APPROVED** [review]
Looks good to me!

**Comment by ifarzana** [comment]
TEST: /Administration/users.cy.js, /Layout/Editor/layout_editor_dataset.cy.js END

**Pull request merged**
