### PR TITLE
Widget: Fix marquee effect implementation from xiboTextRender

### PR DESCRIPTION
**Pull request by rubenpingol-xibo**
relates to xibosignage/xibo#3388

### CODE REVIEW

**Review by maurofmferrao — APPROVED** [review]

**Comment by rubenpingol-xibo** [comment]
I believe that the deleted lines here are not necessary anymore since we have moved the template animation being handled by `onTemplateVisible` using `xiboLayoutAnimate`. But I'm not certain yet if we still need those deleted lines here for module only.

**Comment by rubenpingol-xibo** [comment]
Can you confirm @maurofmferrao?

**Comment by maurofmferrao** [comment]
> Can you confirm @maurofmferrao?

I think that makes sense, but we need just to make sure all modules/templates that were using `xiboTextRender` also run `xiboLayoutAnimate`. 

What happens if we have a template that needs to be animated on `onTemplateRender` and not on `onTemplateVisible`? Do we ever want to do that @dasgarner ?

**Comment by maurofmferrao** [comment]
We also need to test if the behaviour change on the editor, it might not start the animation on resizing :/

**Comment by rubenpingol-xibo** [comment]
> We also need to test if the behaviour change on the editor, it might not start the animation on resizing :/

Yes, I think this makes sense and I can see it's not animating now on resize. I can add `isEditor` to its condition

**Comment by maurofmferrao** [comment]
> > We also need to test if the behaviour change on the editor, it might not start the animation on resizing :/
> 
> Yes, I think this makes sense and I can see it's not animating now on resize. I can add `isEditor` to its condition

Not sure we want that, what if in a different widget we want to run on load and not on visible, even on a player?

The question is: why is `pauseEffectOnStart` false and running those lines since its default value is true?

**Comment by rubenpingol-xibo** [comment]
> > > We also need to test if the behaviour change on the editor, it might not start the animation on resizing :/
> > 
> > 
> > Yes, I think this makes sense and I can see it's not animating now on resize. I can add `isEditor` to its condition
> 
> Not sure we want that, what if in a different widget we want to run on load and not on visible, even on a player?
> 
> The question is: why is `pauseEffectOnStart` false and running those lines since its default value is true?

I think `pauseEffectOnStart` is being set to **false** on `editor-render.js` since it's being set to have a default **false** value

**Comment by rubenpingol-xibo** [comment]
No, I think it's also being set to have default value of **false** on `xibo-player`.

**Comment by maurofmferrao** [comment]
Yeah, it's being set as false on those two places, but maybe the fix is just to set it as `true` by default?

I think that we want the render to always pause on start except when we force it to start right away, on a specific module or on the editor. So we still need to check if it's the editor to start the animation, maybe do that in `editor-render.js` instead of in `xiboTextRender`?

**Comment by rubenpingol-xibo** [comment]
Yes, I think we should proceed with this.

**Review by maurofmferrao — APPROVED** [review]
Looks good to me!

**Comment by dasgarner** [comment]
TEST: /Layout END

**Pull request merged**
