### PR TITLE
Layout Preview: Fix text element fit to selection

### PR DESCRIPTION
**Pull request by rubenpingol-xibo**
relates to xibosignage/xibo#3475

### CODE REVIEW

**Review by dasgarner — APPROVED** [review]
Approved on the understanding we will create a new issue to refactor so that we do not need this type of conditional logic.

**Comment by rubenpingol-xibo** [comment]
> Approved on the understanding we will create a new issue to refactor so that we do not need this type of conditional logic.

Opened a ticket for this here
https://github.com/xibosignageltd/xibo-private/issues/834

**Comment by ifarzana** [comment]
TEST: /Layout END

**Comment by ifarzana** [comment]
TEST:/Layout/Editor/layout_editor_rss_ticker.cy.js END

**Pull request merged**
