### PR TITLE
Layout/Playlist Editor: minimum resolution

### PR DESCRIPTION
**Pull request by maurofmferrao**
relates to xibosignage/xibo#2720

### CODE REVIEW

**Comment by gracec20** [comment]
TEST: /Layout END

**Comment by gracec20** [comment]
TEST: /Layout/layout_editor_mastodon.cy.js END

**Review by ifarzana — APPROVED** [review]
Approving to rebuild container

**Comment by gracec20** [comment]
TEST: /Layout/Editor/layout_editor_mastodon.cy.js END

**Pull request merged**
