### PR TITLE
Elements: Fix error when evaluating elements for preview canvas

### PR DESCRIPTION
**Pull request by rubenpingol-xibo**
relates to xibosignage/xibo#3239

### CODE REVIEW

**Review by maurofmferrao — APPROVED** [review]
Looks good to me!

**Comment by rubenpingol-xibo** [comment]
Test: all

**Comment by rubenpingol-xibo** [comment]
Test: /Layout END

**Comment by rubenpingol-xibo** [comment]
TEST: /Layout END

**Pull request merged**
