### PR TITLE
Elements: Fix preview layout content flashing

### PR DESCRIPTION
**Pull request by rubenpingol-xibo**
relates to xibosignage/xibo#3195

### CODE REVIEW

**Review by maurofmferrao — DISMISSED** [review]
Looks good to me!

**Comment by ifarzana** [comment]
TEST: /Layout END

**Review by dasgarner — CHANGES_REQUESTED** [review]
Needs the changes we discussed

**Comment by rubenpingol-xibo** [comment]
@dasgarner @maurofmferrao, I think we still need few changes here on `html-preview.js`. The one with adding back `iframe.src = iframe.src` and setting the iframe visibility as a fix for the flashing issue.

**Pull request closed without merging**
