### PR TITLE
Display: Non-destructive feature should include send command

### PR DESCRIPTION
**Pull request by mgbaybay**
## Changes
- Add `Send Command` in non-destructive feature

Relates to: https://github.com/xibosignage/xibo/issues/3533

### CODE REVIEW

**Review by nadzpogi — COMMENTED** [review]
I might be mistaken, but I think you should also add this:

```
!$this->getUser()->featureEnabled('displays.limitedView')
```

in lib/Controller/DisplayGroup.php at  line 2513

**Comment by mgbaybay** [comment]
> I might be mistaken, but I think you should also add this:
> 
> ```
> !$this->getUser()->featureEnabled('displays.limitedView')
> ```
> 
> in lib/Controller/DisplayGroup.php at line 2513

You're right, thank you for this! Please see latest [commit ](https://github.com/xibosignage/xibo-cms/pull/2768/commits/8d93d3e5b36800d349bddd5c16dad9d06775d77f). :)

**Review by nadzpogi — APPROVED** [review]
All good!

**Comment by gracec20** [comment]
TEST: /Administration, /Display END

**Pull request merged**
