### PR TITLE
Bring back Delete confirmation modals

### PR DESCRIPTION
**Pull request by maurofmferrao**
relates to xibosignageltd/xibo-private#661

### CODE REVIEW

**Review by dasgarner — APPROVED** [review]

**Comment by ifarzana** [comment]
TEST: /Layout, /Library END

**Comment by ifarzana** [comment]
TEST: /Layout/Editor/layout_editor_clock.cy.js, /Layout/Editor/layout_editor_dataset.cy.js, /Layout/Editor/layout_editor_rss_ticker.cy.js END

**Comment by ifarzana** [comment]
TEST: /Layout/Editor/layout_editor_clock.cy.js, /Layout/Editor/layout_editor_dataset.cy.js, /Layout/Editor/layout_editor_rss_ticker.cy.js END

**Review by ifarzana — APPROVED** [review]
Approving to build PR

**Pull request merged**
