### PR TITLE
New feature: Allow using CAS for the authentication of users.

### PR DESCRIPTION
**Pull request by moobyfr**
Local accounts are still available
Code is based on the SAMLAuthentication
The needed settings are:
```
$authentication = new \Xibo\Middleware\CASAuthentication();
$casSettings = array(
    'config' => array (
        'server' => 'your.cas.server',
        'port' => '443',
        'uri' => '/cas'
    )
);
```

### CODE REVIEW

**Comment by dasgarner** [comment]
Thanks a lot for this PR - we will take a look at it asap! Best wishes, Dan.

**Comment by moobyfr** [comment]
There is still a problem on the `composer.json`, between required dev-packages:
* `xibosignage/oauth2-xibo-cms` needs `league/oauth2-client` which need `phpunit/phpunit: ^5.7|^6.0`
* `apereo/phpcas`needs `phpunit/phpunit: ~3.7.10`
* `infostars/picofeed`needs `phpunit/phpunit: 4.8.26`

I have forced the add of `apereo/phpcas` in `composer.json` because I don't know how to resolve these dependencies.

**Comment by dasgarner** [comment]
Sorry for the delay, I have been learning a bit about CAS.

If CAS authentication is enabled my feeling is what we would want to only provide CAS and not both? I notice that both are provided at the moment.

If we only provide CAS then we could pop a new login.twig file in there for CAS and direct to that accordingly.

I will pull your branch and see if I can understand the composer issue - lots of different libraries require different phpunit versions, so I am not clear what the issue is at the moment.

**Comment by moobyfr** [comment]
I kept the login form authentication, to allow to keep local accounts, at least for the admin. If it's fine to keep only CAS for authentication, it's fine too for our need.

**Comment by dasgarner** [comment]
It would be clearer for us to have CAS only if possible - would you mind making that change, or shall I?

**Comment by dasgarner** [comment]
jenkins
test this please

**Comment by moobyfr** [comment]
I'll look at it tonight

**Comment by moobyfr** [comment]
I have made bad merge in my branch, I'll remake correct merge request

**Pull request closed without merging**
