### PR TITLE
Layouts: Fix Canvas only layouts should set their duration from any images added or a 10 second minimum

### PR DESCRIPTION
**Pull request by mgbaybay**
## Changes
- Fix Canvas only layouts should set their duration from any images added or a 10 second minimum

Relates to: https://github.com/xibosignage/xibo/issues/3499

### CODE REVIEW

**Review by dasgarner — APPROVED** [review]

**Comment by ifarzana** [comment]
TEST: /Display END

**Review by dasgarner — APPROVED** [review]

**Comment by gracec20** [comment]
TEST: /Layout END

**Comment by gracec20** [comment]
TEST: /Display, /Layout/Editor/layout_editor_dataset.cy.js, /Layout/Editor/layout_editor_rss_ticker.cy.js END

**Comment by gracec20** [comment]
TEST: /Layout/Editor/layout_editor_dataset.cy.js, /Layout/Editor/layout_editor_rss_ticker.cy.js END

**Pull request merged**
