### PR TITLE
Layout Preview: First integration of Xibo Layout Renderer

### PR DESCRIPTION
**Pull request by rubenberttpingol**
relates to xibosignage/xibo#2451

### CODE REVIEW

**Comment by dasgarner** [comment]
This looks good Ruben! Before it's going to work, we need to have a discussion about making the XLR repository public - lets try to do that tomorrow.

**Review by maurofmferrao — APPROVED** [review]
Looks good to me!

**Review by ifarzana — APPROVED** [review]
Approve to rebuild container

**Review by maurofmferrao — APPROVED** [review]
Looks good to me!

**Review by dasgarner — APPROVED** [review]

**Comment by dasgarner** [comment]
I think we can make one minor tweak to the source library, so that the latest xibosignage.com URL is mentioned in the copyright comments - this is not a priority for this PR though.

**Review by maurofmferrao — APPROVED** [review]

**Comment by ifarzana** [comment]
TEST: /Layout, /Library END

**Comment by ifarzana** [comment]
TEST: /Library/playlists.cy.js END

**Pull request merged**
