### PR TITLE
Layout: add API to clear layout canvas

### PR DESCRIPTION
**Pull request by dasgarner**
This PR also bumps the version number in Kopff to 4.2.0-alpha.

### CODE REVIEW

**Review by maurofmferrao — APPROVED** [review]
Looks good to me!

**Review by maurofmferrao — DISMISSED** [review]
Looks good to me!

**Comment by ifarzana** [comment]
TEST: /Layout END

**Comment by ifarzana** [comment]
TEST: /Layout/Editor/layout_editor_mastodon.cy.js END

**Review by maurofmferrao — APPROVED** [review]

**Pull request merged**
