### PR TITLE
Property Panel doesn't move target when changing between Elements

### PR DESCRIPTION
**Pull request by maurofmferrao**
relates to xibosignage/xibo#3352

### CODE REVIEW

**Review by dasgarner — APPROVED** [review]

**Comment by maurofmferrao** [comment]
TEST: /Layout/Editor END

**Comment by dasgarner** [comment]
TEST: /Layout/Editor END

**Comment by dasgarner** [comment]
TEST: /Layout/Editor END

**Comment by dasgarner** [comment]
TEST: /Layout/Editor END

**Comment by dasgarner** [comment]
TEST: /Layout/Editor END

**Comment by dasgarner** [comment]
TEST: /Layout/Editor END

**Review by dasgarner — APPROVED** [review]

**Pull request merged**
