### PR TITLE
CSP error with XLR integration

### PR DESCRIPTION
**Pull request by rubenberttpingol**
relates to xibosignageltd/xibo-private#750

### CODE REVIEW

**Review by maurofmferrao — APPROVED** [review]
Looks good to me!

**Comment by ifarzana** [comment]
TEST: /Layout END

**Comment by ifarzana** [comment]
TEST:/Library END

**Comment by ifarzana** [comment]
TEST: /Library/playlists.cy.js END

**Comment by rubenpingol-xibo** [comment]
@ifarzana, tests are now successful. Please let me know once approved for merge. Thank you!

**Pull request merged**
