### PR TITLE
Playlists: dynamic playlists should filter media by folderId

### PR DESCRIPTION
**Pull request by nadzpogi**
relates to xibosignageltd/xibo-private#841

### CODE REVIEW

**Review by mgbaybay — APPROVED** [review]
Nice!

**Review by mgbaybay — APPROVED** [review]

**Review by ifarzana — APPROVED** [review]
Approving to build container

**Review by mgbaybay — APPROVED** [review]

**Review by mgbaybay — APPROVED** [review]

**Review by mgbaybay — APPROVED** [review]

**Comment by ifarzana** [comment]
TEST: /Layout/Editor/layout_editor_populated.cy.js, /Library END

**Comment by ifarzana** [comment]
TEST: /Library/datasets.cy.js END

**Comment by ifarzana** [comment]
TEST: login.cy.js END

**Pull request merged**
