### PR TITLE
RSS element: Repeat items and Pinned slots shows less number of items in preview

### PR DESCRIPTION
**Pull request by rubenberttpingol**
relates to xibosignage/xibo#3367

### CODE REVIEW

**Review by maurofmferrao — APPROVED** [review]
Looks good to me!

**Comment by ifarzana** [comment]
TEST: /Layout END

**Comment by ifarzana** [comment]
TEST: /Layout/Editor/layout_editor_dataset.cy.js END

**Comment by ifarzana** [comment]
TEST: /Layout/Editor/layout_editor_rss_ticker.cy.js END

**Pull request merged**
