### PR TITLE
Schedule: tidy up criteria for alpha

### PR DESCRIPTION
**Pull request by dasgarner**
relates to xibosignageltd/xibo-private#459

### CODE REVIEW

**Review by PeterMis — APPROVED** [review]

**Comment by ifarzana** [comment]
TEST: /Schedule END

**Comment by dasgarner** [comment]
TEST: /Schedule END

**Comment by ifarzana** [comment]
TEST: /Schedule END

**Comment by ifarzana** [comment]
TEST: /Schedule END

**Pull request merged**
