### PR TITLE
XLR: Fix for webpage content rendering

### PR DESCRIPTION
**Pull request by rubenberttpingol**
relates to xibosignage/xibo#3451

### CODE REVIEW

**Review by maurofmferrao — DISMISSED** [review]

**Comment by gracec20** [comment]
TEST: /Layout END

**Comment by gracec20** [comment]
TEST: /Layout/Editor/layout_editor_dataset.cy.js, /Layout/Editor/layout_editor_rss_ticker.cy.js END

**Comment by rubenpingol-xibo** [comment]
Hey @maurofmferrao, needs your re-approval for this PR. Needed to resolve conflicts

**Review by maurofmferrao — APPROVED** [review]

**Comment by rubenpingol-xibo** [comment]
@gracec20 We might need to re-run the github-actions here. Thank you! 🙂

**Comment by rubenpingol-xibo** [comment]
TEST: /Layout END

**Comment by dasgarner** [comment]
After reviewing the XLR repository develop branch, I believe that the current contents of the CMS develop branch package.json is actually already includes the above changes 

image

**Pull request closed without merging**
