### PR TITLE
Misc issues 4.0.6

### PR DESCRIPTION
**Pull request by dasgarner**
- Hide canvas region from the thumbnail unless it is the only region. Ensure the thumbnail is generated on publish.
 - Format menu board price with 2 decimals on the data entry and widget
 - Fix an error on the user grid when a user has a null homepage
 - XMDS report fault should protect against super long reasons
 - Fix Ad Campaigns add/edit so that impression type can be used

### CODE REVIEW

**Comment by dasgarner** [comment]
TEST: all

**Comment by dasgarner** [comment]
TEST: all END

**Review by ifarzana — APPROVED** [review]
Looks good to me. However, we might want to show `Impressions` instead of imp in grid (Target Type)

**Review by ifarzana — APPROVED** [review]

**Comment by dasgarner** [comment]
TEST: /Layout/Editor/layout_editor_dataset.cy.js END

**Pull request merged**
