### PR TITLE
Adds Text Description field to Text/Webpage Media Typess.  Fixes Issye https://github.com/xibosignage/xibo/issues/178

### PR DESCRIPTION
**Pull request by andyrogers2012**

### CODE REVIEW

**Comment by andyrogers2012** [comment]
Updated Forecast I/O to include Colour dialog box upon adding new media
https://github.com/xibosignage/xibo/issues/289

**Comment by andyrogers2012** [comment]
Updated Forecast I/O again to include Text Description field 
https://github.com/xibosignage/xibo/issues/290

**Comment by Speedy-Gonzalez** [comment]
Please don't mix up different changes in one pull request.

You should work with topic branches. Working with topic branches allows you to create more than one pull request and so different topics are not mixed in one pull request.

See for more details:
http://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell
http://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows
http://git-scm.com/book/en/v2/GitHub-Account-Setup-and-Configuration
(all URLs link to the first page of each chapter. You can find more by clicking on "Chapters" or on "next").

Please make it as easy as possible for Dan to understand, test and merge your commits.

Thanks.

**Comment by andyrogers2012** [comment]
Oh sorry, forgo about the branching side of things.  This is my first time using git push, commit etc.
Dan do you want me to split these commit's out into separate branch's and do separate Pull Request's or can I leave these in one Pull Commit commit on this occasion?

I honestly didn't know about needing to do separate pull requests for each different type of change.  Thought doing separate commits on each issue was correct.

Thanks

Andy

**Comment by dasgarner** [comment]
Haha, well firstly thank you for the contributions! Much appreciated. Secondly, I was rather confused for a while :smile: 

No need to separate them out this time, I have worked through it and your changes look great.

In future branches for each change would be preferable - so you would have created:
 - Name field
 - Missing Colour Field
 - Date Array Correction

But as I say, don't worry about that for this time around, i'll merge this in.

**Comment by Speedy-Gonzalez** [comment]
@andyrogers2012 No problem. I just wanted to say, that there is a "better" (let's say much less confusing) way to contribute to a project :smile:

**Pull request merged**
