### PR TITLE
Widgets: Fix currencies flags and icon

### PR DESCRIPTION
**Pull request by rubenpingol-xibo**
relates to xibosignageltd/xibo-private#440

### CODE REVIEW

**Comment by dasgarner** [comment]
I think we may have already fixed this issue in this PR: https://github.com/xibosignage/xibo-cms/pull/2021

We had a similar issue with weather icons where the `autoInclude` property wasn't working as expected.

**Comment by dasgarner** [comment]
See flags working without this PR already:

image

**Comment by rubenpingol-xibo** [comment]
Yes, as I have updated my branch on this PR and tested it, I can confirm that the changes in this PR are not necessary anymore.

> I think we may have already fixed this issue in this PR: #2021
> 
> We had a similar issue with weather icons where the `autoInclude` property wasn't working as expected.

**Comment by dasgarner** [comment]
Thanks Ruben, and sorry for the wasted effort. I'll close this out then.

**Pull request closed without merging**
