### PR TITLE
Feature/multiple fixes 4.0.8

### PR DESCRIPTION
**Pull request by maurofmferrao**

### CODE REVIEW

**Comment by maurofmferrao** [comment]
TEST: all

**Comment by maurofmferrao** [comment]
TEST: all

**Comment by maurofmferrao** [comment]
TEST: all

**Comment by maurofmferrao** [comment]
TEST: /Layout/Editor /Schedule END

**Comment by maurofmferrao** [comment]
TEST: /Layout/Editor, /Schedule END

**Review by PeterMis — APPROVED** [review]

**Pull request merged**
