### PR TITLE
Playlist Editor: Delete button not working and Back button needs to be removed

### PR DESCRIPTION
**Pull request by maurofmferrao**
relates to xibosignage/xibo#3355

### CODE REVIEW

**Comment by ifarzana** [comment]
TEST: /Library END

**Comment by ifarzana** [comment]
TEST: /Library END

**Comment by dasgarner** [comment]
TEST: /Library END

**Comment by dasgarner** [comment]
TEST: /Library END

**Comment by dasgarner** [comment]
TEST: /Library END

**Comment by dasgarner** [comment]
TEST: /Library END

**Comment by dasgarner** [comment]
TEST: /Library END

**Pull request merged**
