### PR TITLE
Mastodon: Fix for item direction horizontal setting and overflow text

### PR DESCRIPTION
**Pull request by rubenpingol-xibo**
relates to xibosignageltd/xibo-private#796

### CODE REVIEW

**Review by maurofmferrao — APPROVED** [review]
Looks good to me!

**Comment by gracec20** [comment]
TEST: /Layout END

**Comment by gracec20** [comment]
TEST: /Layout/Editor/layout_editor_dataset.cy.js , /Layout/Editor/layout_editor_mastodon.cy.js END

**Comment by gracec20** [comment]
TEST: /Layout/Editor/layout_editor_mastodon.cy.js END

**Pull request merged**
