### PR TITLE
Mastodon widgets / templates no date formatting

### PR DESCRIPTION
**Pull request by maurofmferrao**
relates to xibosignage/xibo#3281

### CODE REVIEW

**Comment by dasgarner** [comment]
Quick question - why does removing the date format help?

**Comment by maurofmferrao** [comment]
> Quick question - why does removing the date format help?

We had extra Date Format in some templates that don't have date in the provider data object ( Currency and Stocks ), should we keep Date Format on those? 🤔

**Review by rubenpingol-xibo — APPROVED** [review]

**Comment by maurofmferrao** [comment]
TEST: /Layout/Editor END

**Comment by mrdanleey** [comment]
I installed Xibo 4.0.7 with this fix, but still seeing no date formatting when previewing in the cms. Is this correct? Did not test it on a player yet.

**Pull request merged**
