### PR TITLE
Refactored and UnitTested - xibosignage/xibo#1414

### PR DESCRIPTION
**Pull request by LukyLuke**
Finally :o)
Was more work than I thought, but now I found a good solution for most of graphs and charts.
What I didn't do is the "Y-Constant line" which is more a feature for release 2.0 where I planned to combine different datasets and graph types on one view.

I refactored a lot and made some unit tests for the different calculations and reorderings which are needed.

If you have a minute for checking on remove the cached stuff when a dataset is changed, that would be amazing. Or give me a hint where I can look at.

### CODE REVIEW

**Comment by LukyLuke** [comment]
Test this please

**Comment by dasgarner** [comment]
This looks great - I'll run the test suite over it to go through your new tests and then i'll merge it in an run through it on a local CMS!

**Comment by dasgarner** [comment]
The test suite failed with the following message:

```
PHP Fatal error:  Uncaught TypeError: Return value of Xibo\Tests\Widget\WidgetBase::getInstance() must be an instance of Xibo\Tests\Widget\object, instance of Xibo\Widget\Graph returned in /var/www/cms/tests/Widget/WidgetBase.php:109
Stack trace:
#0 /var/www/cms/tests/Widget/GraphTest.php(40): Xibo\Tests\Widget\WidgetBase->getInstance('Xibo\\Widget\\Gra...')
#1 /var/www/cms/vendor/phpunit/phpunit/src/Framework/TestSuite.php(461): Xibo\Tests\Widget\GraphTest->__construct()
#2 /var/www/cms/vendor/phpunit/phpunit/src/Framework/TestSuite.php(860): PHPUnit_Framework_TestSuite::createTest(Object(ReflectionClass), 'testIsValid')
#3 /var/www/cms/vendor/phpunit/phpunit/src/Framework/TestSuite.php(175): PHPUnit_Framework_TestSuite->addTestMethod(Object(ReflectionClass), Object(ReflectionMethod))
#4 /var/www/cms/vendor/phpunit/phpunit/src/Framework/TestSuite.php(281): PHPUnit_Framework_TestSuite->__construct(Object(ReflectionClass))
#5 /var/www/cms/vendor/phpunit/phpunit/src/Framework/TestSuite.php(367): PHPUnit_Framework_TestSuite->addT in /var/www/cms/tests/Widget/WidgetBase.php on line 109
```

I think that's a method you've added? Perhaps you could take a quick look! Thanks.

**Comment by LukyLuke** [comment]
test this please

**Comment by LukyLuke** [comment]
Seems I have a little older PHP-Version :o)
Let's try it like this...

**Comment by dasgarner** [comment]
test this please

**Comment by dasgarner** [comment]
Fantastic, that looks a lot better. I'll get that merged in today and pulled to a local branch so I can run it up and see how it works.

Thanks as usual!!

**Comment by dasgarner** [comment]
Quick question if I may - why do we limit the columns to plot to value columns? Wouldn't formula's be just as valid?

**Comment by LukyLuke** [comment]
I have not tried out formulas. If the resulting value is a number, yes, this should work as well.
Let's give it a chance :)

**Pull request merged**
