### PR TITLE
Layout Preview: Circle and Date/Time not being rendered #808

### PR DESCRIPTION
**Pull request by rubenpingol-xibo**
relates to xibosignageltd/xibo-private#808

### CODE REVIEW

**Review by maurofmferrao — APPROVED** [review]
Looks good!

**Comment by gracec20** [comment]
TEST: /Layout END

**Comment by gracec20** [comment]
TEST: /Layout/Editor/layout_editor_dataset.cy.js, /Layout/Editor/layout_editor_mastodon.cy.js, /Layout/Editor/layout_editor_rss_ticker.cy.js END

**Comment by gracec20** [comment]
TEST: /Layout/Editor/layout_editor_mastodon.cy.js END

**Pull request merged**
