### PR TITLE
Security Fix: Github workflow input validation

### PR DESCRIPTION
**Pull request by ifarzana**
- Related to https://github.com/xibosignageltd/xibo-private/issues/758

Regex Validation and use of GitHub Actions environment variable

### CODE REVIEW

**Review by dasgarner — APPROVED** [review]

**Comment by ifarzana** [comment]
TEST: login.cy.js END

**Comment by ifarzana** [comment]
non test code in comment for test prupose

**Comment by ifarzana** [comment]
TEST: not ending

**Comment by ifarzana** [comment]
non test code again in comment for test pr

**Comment by ifarzana** [comment]
TEST: login.cy.js END

**Pull request merged**
